version: 2.1

# Define the jobs we want to run for this project
jobs:
  lint:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-yarn-deps-{{ checksum "yarn.lock" }}
            - v1-yarn-deps-
      - run:
          name: "Install Dependencies"
          command: |
            yarn install
      - save_cache:
          key: v1-yarn-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: "Lint Commits"
          command: |
            yarn lint

# Orchestrate our job run sequence
workflows:
  lint:
    jobs:
      - lint
